#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port5,  bumper,         sensorVexIQ_Touch)
#pragma config(Sensor, port8,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, lightSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor7,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your robot. This program will use
  "Arcade Mode" to enable one joysticks to drive the two main motors of the Robot.

  The 4 joystick axis on the VEX IQ Wireless Controller return values from -127 to +127.

------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		//Set the speed of the two motors the value from the two joystick values in the formula.
		setMotorSpeed(leftMotor,  (getJoystickValue(ChA) - getJoystickValue(ChB))/2);  	// (y - x)/2
		setMotorSpeed(rightMotor, (getJoystickValue(ChA) + getJoystickValue(ChB))/2);  	// (y + x)/2
	}
}
