#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          liftStage1,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          liftStage2,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          claw,          tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//* EXAMPLE Code with Functions ******************************************************
//*
//* Code uses two functions one for the joySticks and one for the Buttons
//*    This allows us to much simpler call the what we want todo with buttons
//*    and Joystick and allows us to to reuse code
//*
//***********************************************************************************

int threshold = 10;				// control deadstick area

//* JoyStick Functions **************************************************************
void joystick(TVexJoysticks channel_letter, int motor_name)
{
	if(getJoystickValue(channel_letter) > threshold || getJoystickValue(channel_letter) < threshold) {
		setMotorSpeed(motor_name, getJoystickValue(channel_letter));
		} else {
		setMotorSpeed(motor_name, 0);
	}
}

//* Button Functions **************************************************************
void button(TVexJoysticks button_up, TVexJoysticks button_down, int motor_name, int how_fast)
{
	if(getJoystickValue(button_up) == 1 ) {
		setMotorSpeed(motor_name, how_fast);
		} else if (getJoystickValue(button_down) == 1) {
		setMotorSpeed(motor_name, -how_fast);
		} else {
		setMotorSpeed(motor_name, 0);
	}
}

//* MAIN Task ********************************************************************
task main()
{
	//* Read Joystick contineously
	while(true)
	{
		joystick(ChA, leftMotor);
		joystick(ChD, rightMotor);

		button(BtnLUp, BtnLDown, liftStage1, 50);
	}
}
