#pragma config(Motor,  motor1,          liftLeft,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          liftRight,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor7,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor11,         centerDrive,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightDrive,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 10;
	while(true)
	{
		if(getJoystickValue(ChA) > threshold || getJoystickValue(ChA) < -threshold)
		{
			setMotorSpeed(leftDrive, getJoystickValue(ChA));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
			setMotorSpeed(leftDrive, 0);
		}

				if(getJoystickValue(ChD) > threshold || getJoystickValue(ChD) < -threshold)
		{
			setMotorSpeed(rightDrive, getJoystickValue(ChD));
		}
		else  //If less than the threshold, we'll set the motor to zero.
		{
			setMotorSpeed(rightDrive, 0);
		}
		// ===== Center Drive Wheel  ==================================================
		//If Button "L-Up" is pressed in, we'll set the arm motor to run in reverse.
		if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(centerDrive, -127);
		}
		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnLDown) == 1)
		{
			setMotorSpeed(centerDrive, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(centerDrive, 0);
		}
		// ================ Hanging Lift ==============================================
		//If Button "R-Up" is pressed in, we'll set the arm motor to run in reverse.
		if(getJoystickValue(BtnRUp) == 1)
		{
			setMotorSpeed(liftLeft, -127);
			setMotorSpeed(liftRight, -127);
		}
		//If the "R-Up" isn't pressed, but "R-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnRDown) == 1)
		{
			setMotorSpeed(liftLeft, 127);
			setMotorSpeed(liftRight, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(liftLeft, 0);
			setMotorSpeed(liftRight, 0);
		}
	}
}
