#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port5,  bumper,         sensorVexIQ_Touch)
#pragma config(Sensor, port8,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, lightSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor7,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
This program will swing turn your lobot right and left
------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		setMotorSpeed(leftMotor, -127);		//Set the leftMotor (motor1) to full power reverse (-127)
		setMotorSpeed(rightMotor, 127);  	//Set the rightMotor (motor6) to full power forward (127)
		sleep(1000);											//Wait for 1 second before continuing on in the program.

		setMotorSpeed(leftMotor, 127);		//Set the leftMotor (motor1) to full power forward (127)
		setMotorSpeed(rightMotor, -127);  //Set the rightMotor (motor6) to full power reverse (-127)
		sleep(1000);											//Wait for 1 second before continuing on in the program.
	}
}
