#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port5,  bumper,         sensorVexIQ_Touch)
#pragma config(Sensor, port8,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, lightSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor7,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
This program will drive robot for a set distance and while doing so show the values of the encoder
------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		resetMotorEncoder(leftMotor);		//Reset the current position in the motor encoder to zero.
		resetMotorEncoder(rightMotor);
		moveMotorTarget(leftMotor, 5000, 75);  //Set motor to run 5000 counts at power level 75.
		moveMotorTarget(rightMotor, 5000, 75);

		wait1Msec(50); //Small delay to allow motors time to start moving before checking

		//getMotorMoving - Flag to indiciate if the motor is moving (True - Moving / False - Stopped)
		//Loop while either motor is still moving (Left OR Right is still moving)
		while(getMotorMoving(leftMotor) || getMotorMoving(rightMotor))
		{
			//Print
			displayTextLine(1, "Left Motor: %d", getMotorEncoder(leftMotor));
			displayTextLine(3, "Right Motor: %d", getMotorEncoder(rightMotor));
			sleep(50);
		}
	}
}
