#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port5,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Sensor, port8,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port11, colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Motor,  motor7,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
This is a starting template with a;; the sensor and motor defintions for the simple
two wheeled teaching bot.  You should use this program as a starting point to create your own
TeleOp or Autonomous program.
------------------------------------------------------------------------------------------------*/

task main()
{
	// --------------------------------------------------------------------------------------------
	// Comment below code to execute an autonomous program section below
	// --------------------------------------------------------------------------------------------

	// SAMPLE TelOp program -- note ifininte while loop wrapped aroudn all code
	while(true)													// infinite loop for teleOp - program will run forever
																			// until stopped, and does read remoteControl in atight loop
	{
		setMotorSpeed(leftMotor, getJoystickValue(ChA));	// attach left Joystick to left motor
		setMotorSpeed(rightMotor, getJoystickValue(ChD));	// attach right Joystick to right motor
	}

	// --------------------------------------------------------------------------------------------
	// Un-comment below code to execute an autonomous program
	// --------------------------------------------------------------------------------------------

	//setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
	//setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
	//sleep(2000);										//Wait for 2 seconds before continuing on in the program.
}
