#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port5,  bumper,         sensorVexIQ_Touch)
#pragma config(Sensor, port8,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port11, lightSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor7,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program will use
  "Tank Mode" to enable two joysticks to drive the two main motors of the Robot.

  The 4 joystick axis on the VEX IQ Wireless Controller return values from -127 to +127.

------------------------------------------------------------------------------------------------*/

task main()
{
	while(true)
	{
		setMotorSpeed(leftMotor, getJoystickValue(ChA));
		setMotorSpeed(rightMotor, getJoystickValue(ChD));

		if(getJoystickValue(BtnLUp) == 1)
		{
			setTouchLEDRGB(touchLED, 200, 100, 0);
  		setTouchLEDBlinkTime(touchLED, 40, 10);
  		sleep(10000);
  		setTouchLEDBlinkTime(touchLED, 0, 0);
		}
	}
}
